defaultBaseImage: gcr.io/distroless/static-debian12:nonroot

builds:
  - id: hearts
    main: ./cmd/hearts
    env:
      - CGO_ENABLED=0
      - LOG_LEVEL=warn
    flags:
      - -trimpath
    ldflags:
      - -s -w
